#!/usr/bin/env python3

import rclpy
from rclcppyy import Node


def main():
    rclpy.init()
    
    node = Node('target_node')
    node.get_logger().info('Target script is running!')
    
    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.get_logger().info('Shutting down...')
        node.destroy_node()
        rclpy.shutdown()


if __name__ == '__main__':
    main() 